# [CircleCI](https://circleci.com).
---
version: 2.1
jobs:
  build:
    machine:
      image: default
    steps:
      - checkout
      - run:
          name: Tests
          command: ./tests/test.sh
